apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    backstage.io/managed-by-location: url:https://github.com/devesh-harness/python-pipeline-samples/tree/patch-3/catalog-info.yaml
    backstage.io/managed-by-origin-location: url:https://github.com/devesh-harness/python-pipeline-samples/blob/patch-3/catalog-info.yaml
    backstage.io/view-url: https://github.com/devesh-harness/python-pipeline-samples/tree/patch-3/catalog-info.yaml
    backstage.io/edit-url: https://github.com/devesh-harness/python-pipeline-samples/edit/patch-3/catalog-info.yaml
    backstage.io/source-location: url:https://github.com/devesh-harness/python-pipeline-samples/tree/patch-3/
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-id: 43877214ldddddddddd
    jira/project-key: IDP
    jenkins.io/github-folder: CDS-68313
    firehydrant.com/service-name: pythonddddddddddddd
    backstage.io/kubernetes-label-selector: app=idp-ui00000
    backstage.io/kubernetes-namespace: 63feee14cbf66e3c798c4bdc
    github.com/project-slug: vigneswara-propelo/python-pipeline-samples
    harness.io/pipelines: >
      Build:
      https://laxmiharness.pr2.harness.io/ng/account/6cBjZs_fTWCiRITqFyRrgQ/module/ci/orgs/default/projects/IDP/pipelines/TestUpdateCatalog/pipeline-studio/?storeType=INLINE
    grafana/dashboard-selector: (tags @> 'prometheus' || tags @> 'blackbox')
    pagerduty.com/service-id: PT5ED69
  name: devesh-test
  tags:
    - python-test
    - python123
  uid: fe103da5-70e9-4554-bff7-04f3637a9fd5
  etag: ad584aa63f4f9301f227b22a89469bb86e0e6ed0
spec:
  type: service
  lifecycle: experimental
  owner: default:harness_account_all_users
  providesApis:
    - idp-Service-api
