apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  annotations:
    backstage.io/managed-by-location: url:https://app.harness.io/Group/default/_account_all_users
    backstage.io/managed-by-origin-location: url:https://app.harness.io/Group/default/_account_all_users
    backstage.io/view-url: https://app.harness.io/Group/default/_account_all_users
  name: ug
  namespace: default
  title: All Account Users
  created_by: Harness
  uid: e2b874b9-2c3e-4936-9b53-103f2a069391
  etag: def0074ea5f47d560293d3362d08903a274951d3
spec:
  children: []
  members:
    - admin@harness.io
  type: team
