apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ug
  namespace: default
  title: ug
  created_by: Harness
  uid: e2b874b9-2c3e-4936-9b53-103f2a069391
  etag: def0074ea5f47d560293d3362d08903a274951d3
spec:
  children: []
  members:
    - user:default/admin@harness.io
  type: team
